orbits:
  orbit1:
    catnr: 39084
  orbit2:
    line1: 1 49260U 21088A   22166.94778099  .00000339  00000+0  85254-4 0  9992
    line2: 2 49260  98.2276 237.1831 0001142  78.2478 281.8849 14.57099002 38060
  orbit3:
    epoch: '2022-06-16T17:54:00Z'
    # semi-major axis (m)
    a: 7080 km
    # eccentricy
    e: 0.0008685
    # inclination
    i: 85 deg
    # raan
    omega: 261.4942 deg
    # argument of perigee
    w: 246.9642 deg
    # true anomaly
    #v:
    # mean anomaly
    m: 257.7333 deg

step: PT10M

propagator_args:
  mass: 200kg
  positionTolerance: 10.0
  considerGravity: true
  gravityFieldDegree: 2
  gravityFieldOrder: 2
  considerSolarPressure: True
  solarPressureCrossSection: "0.344 m^2"
  solarCa: 0.2
  solarCs: 0.8
  considerAtmosphere: true
  atmosphereCrossSection: 0.344 m^2
  atmosphereDragCoeff: 2.2
  bodies: ["sun", "moon", "jupiter"]