name: orbit-tool
channels:
  - conda-forge
dependencies:
  - astropy
  - czml3
  - isodate
  - matplotlib
  - orekit=11.2
  - pandas
  - pip
  - python=3.10.4
  - pyyaml
  - requests
  - geopy=2.0.0
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - flake8
  - pip:
    - git+https://github.com/greyskyy/orekit-factory.git@v0.1.0
    - cesiumpy
