name: orbit-tool
channels:
  - conda-forge
dependencies:
  - isodate
  - orekit=11.2
  - pip
  - python=3.10.4
  - pyyaml
  - requests
  - astropy
  - pandas
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - flake8
  - pip:
    - git+https://github.com/greyskyy/orekit-factory.git
